package workflow

import (
	"bytes"
	"context"
	"errors"
	"log"
	"reflect"
	"strings"
	"testing"
	"time"
)

func TestNewRunContextGeneratesRunID(t *testing.T) {
	rc := NewRunContext(nil, nil, nil)
	if rc.RunID == "" {
		t.Fatal("RunID should be generated by default")
	}
	if rc.Context == nil {
		t.Fatal("Context should default to context.Background")
	}
	if rc.Shared == nil {
		t.Fatal("Shared should default to a non-nil store")
	}
}

func TestEventSinkPanicIsRecovered(t *testing.T) {
	var logs bytes.Buffer
	rc := NewRunContext(context.Background(), nil, nil)
	rc.Logger = log.New(&logs, "", 0)
	rc.Events = EventSinkFunc(func(event Event) {
		panic("sink failed")
	})

	rc.Emit(Event{Type: EventFlowStarted})

	if !strings.Contains(logs.String(), "workflow event sink panic") {
		t.Fatalf("expected event sink panic log, got %q", logs.String())
	}
}

func TestAsyncEventSink(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	received := make(chan Event, 2)
	sink := NewAsyncEventSink(ctx, 2, EventSinkFunc(func(event Event) {
		received <- event
	}))

	sink.Emit(Event{Type: EventFlowStarted})
	sink.Emit(Event{Type: EventFlowFinished})
	sink.Close()

	got := []EventType{(<-received).Type, (<-received).Type}
	want := []EventType{EventFlowStarted, EventFlowFinished}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("events = %#v, want %#v", got, want)
	}
}

func TestAsyncEventSinkLifecycleEdges(t *testing.T) {
	t.Run("close is idempotent and emit after close is ignored", func(t *testing.T) {
		sink := NewAsyncEventSink(context.Background(), 1, EventSinkFunc(func(event Event) {}))

		sink.Emit(Event{Type: EventFlowStarted})
		sink.Close()
		sink.Close()
		sink.Emit(Event{Type: EventFlowFinished})
	})

	t.Run("context cancellation drains buffered events", func(t *testing.T) {
		ctx, cancel := context.WithCancel(context.Background())
		received := make(chan Event, 2)
		sink := NewAsyncEventSink(ctx, 2, EventSinkFunc(func(event Event) {
			received <- event
		}))

		sink.Emit(Event{Type: EventFlowStarted})
		sink.Emit(Event{Type: EventFlowFinished})
		cancel()
		sink.Close()

		got := []EventType{
			receiveEventType(t, received),
			receiveEventType(t, received),
		}
		want := []EventType{EventFlowStarted, EventFlowFinished}
		if !reflect.DeepEqual(got, want) {
			t.Fatalf("events = %#v, want %#v", got, want)
		}
	})
}

func TestFlowValidate(t *testing.T) {
	t.Run("valid graph", func(t *testing.T) {
		start := NewFuncNode(NodeMeta{ID: "start"})
		end := NewFuncNode(NodeMeta{ID: "end"})
		start.Core().Next(end)

		if err := NewFlow("valid", start).Validate(); err != nil {
			t.Fatalf("Validate returned error: %v", err)
		}
	})

	t.Run("nil start", func(t *testing.T) {
		err := NewFlow("invalid", nil).Validate()
		if err == nil {
			t.Fatal("Validate expected error, got nil")
		}
		var validationErr *ValidationError
		if !errors.As(err, &validationErr) {
			t.Fatalf("error %T should be ValidationError", err)
		}
	})

	t.Run("duplicate node id", func(t *testing.T) {
		start := NewFuncNode(NodeMeta{ID: "start"})
		left := NewFuncNode(NodeMeta{ID: "dup"})
		right := NewFuncNode(NodeMeta{ID: "dup"})
		start.Core().NextAction("left", left)
		start.Core().NextAction("right", right)

		err := NewFlow("duplicate", start).Validate()
		if err == nil || !strings.Contains(err.Error(), "duplicate node id") {
			t.Fatalf("Validate error = %v, want duplicate node id", err)
		}
	})

	t.Run("cycle", func(t *testing.T) {
		a := NewFuncNode(NodeMeta{ID: "a"})
		b := NewFuncNode(NodeMeta{ID: "b"})
		a.Core().Next(b)
		b.Core().Next(a)

		err := NewFlow("cycle", a).Validate()
		if err == nil || !strings.Contains(err.Error(), "cycle") {
			t.Fatalf("Validate error = %v, want cycle", err)
		}
	})

	t.Run("nil successor", func(t *testing.T) {
		start := NewFuncNode(NodeMeta{ID: "start"})
		start.Core().mu.Lock()
		start.Core().successors["nil"] = nil
		start.Core().mu.Unlock()

		err := NewFlow("nil-successor", start).Validate()
		if err == nil || !strings.Contains(err.Error(), "successor node is nil") {
			t.Fatalf("Validate error = %v, want nil successor", err)
		}
	})

	t.Run("nil flow and nil core", func(t *testing.T) {
		var flow *Flow
		if err := flow.Validate(); err == nil {
			t.Fatal("nil flow Validate expected error, got nil")
		}

		err := NewFlow("nil-core", nilCoreNode{}).Validate()
		if err == nil || !strings.Contains(err.Error(), "node core is nil") {
			t.Fatalf("Validate error = %v, want nil core", err)
		}
	})
}

func TestFuncNodePanicIsWorkflowError(t *testing.T) {
	var events []Event
	node := NewFuncNode(NodeMeta{ID: "panic-node"}).
		SetExec(func(ctx *RunContext, prepResult any) (any, error) {
			panic("exec exploded")
		})

	rc := NewRunContext(context.Background(), nil, nil)
	rc.Events = EventSinkFunc(func(event Event) {
		events = append(events, event)
	})

	_, err := node.Run(rc)
	if err == nil {
		t.Fatal("Run expected error, got nil")
	}

	var wfErr *WorkflowError
	if !errors.As(err, &wfErr) {
		t.Fatalf("error %T should be WorkflowError", err)
	}
	if wfErr.Stage != StagePanic || wfErr.NodeID != "panic-node" {
		t.Fatalf("WorkflowError = stage:%s node:%s, want panic/panic-node", wfErr.Stage, wfErr.NodeID)
	}
	if wfErr.Stack == "" {
		t.Fatal("panic WorkflowError should include stack")
	}
	if len(events) != 2 || events[1].Type != EventNodeFailed {
		t.Fatalf("events = %#v, want node started then failed", events)
	}
}

func TestBatchFlowPanicIsWorkflowError(t *testing.T) {
	start := NewFuncNode(NodeMeta{ID: "start"})
	flow := NewBatchFlow("panic-batch-flow", start).
		SetPrepBatch(func(ctx *RunContext) ([]Params, error) {
			panic("prep batch exploded")
		})

	_, err := flow.RunWithContext(NewRunContext(context.Background(), nil, nil))
	if err == nil {
		t.Fatal("RunWithContext expected error, got nil")
	}

	var wfErr *WorkflowError
	if !errors.As(err, &wfErr) {
		t.Fatalf("error %T should be WorkflowError", err)
	}
	if wfErr.Stage != StagePanic {
		t.Fatalf("stage = %s, want panic", wfErr.Stage)
	}
}

func TestNodeTimeout(t *testing.T) {
	node := NewFuncNode(NodeMeta{ID: "timeout"}).
		SetExec(func(ctx *RunContext, prepResult any) (any, error) {
			<-ctx.Done()
			return nil, nil
		})
	node.Core().SetTimeout(10 * time.Millisecond)

	flow := NewFlow("timeout-flow", node)
	_, err := flow.RunWithContext(NewRunContext(context.Background(), nil, nil))
	if err == nil {
		t.Fatal("RunWithContext expected timeout error, got nil")
	}

	var wfErr *WorkflowError
	if !errors.As(err, &wfErr) {
		t.Fatalf("error %T should be WorkflowError", err)
	}
	if wfErr.Stage != StageFlow || wfErr.NodeID != "timeout" {
		t.Fatalf("WorkflowError = stage:%s node:%s, want flow/timeout", wfErr.Stage, wfErr.NodeID)
	}
	if wfErr.Code != ErrCodeTimeout {
		t.Fatalf("code = %s, want %s", wfErr.Code, ErrCodeTimeout)
	}
}

func TestFlowTimeout(t *testing.T) {
	node := NewFuncNode(NodeMeta{ID: "flow-timeout"}).
		SetExec(func(ctx *RunContext, prepResult any) (any, error) {
			<-ctx.Done()
			return nil, nil
		})
	flow := NewFlow("flow-timeout", node).SetTimeout(10 * time.Millisecond)

	_, err := flow.RunWithContext(NewRunContext(context.Background(), nil, nil))
	if err == nil {
		t.Fatal("RunWithContext expected timeout error, got nil")
	}

	var wfErr *WorkflowError
	if !errors.As(err, &wfErr) {
		t.Fatalf("error %T should be WorkflowError", err)
	}
	if wfErr.Code != ErrCodeTimeout {
		t.Fatalf("code = %s, want %s", wfErr.Code, ErrCodeTimeout)
	}
}

func TestFlowAndNodeErrorEdges(t *testing.T) {
	if _, err := NewFlow("nil-start", nil).RunWithContext(nil); err == nil {
		t.Fatal("nil start flow should return error")
	}

	cancelled, cancel := context.WithCancel(context.Background())
	cancel()
	node := NewFuncNode(NodeMeta{ID: "cancelled"})
	_, err := NewFlow("cancelled-flow", node).RunWithContext(NewRunContext(cancelled, nil, nil))
	if err == nil {
		t.Fatal("cancelled context should return error")
	}

	var wfErr *WorkflowError
	if !errors.As(err, &wfErr) || wfErr.Stage != StageFlow {
		t.Fatalf("error = %v, want flow WorkflowError", err)
	}
	if wfErr.Code != ErrCodeCancelled {
		t.Fatalf("code = %s, want %s", wfErr.Code, ErrCodeCancelled)
	}

	if err := sleepContext(cancelled, time.Second); err == nil {
		t.Fatal("sleepContext should return cancellation error")
	}
}

func TestStrictRoutingMissingSuccessor(t *testing.T) {
	start := NewFuncNode(NodeMeta{ID: "start"}).
		SetPost(func(ctx *RunContext, prepResult any, execResult any) (string, error) {
			return "missing", nil
		})
	start.Core().NextAction("known", NewFuncNode(NodeMeta{ID: "known"}))

	_, err := NewFlow("strict", start).SetStrictRouting(true).RunWithContext(NewRunContext(context.Background(), nil, nil))
	if err == nil {
		t.Fatal("strict routing should return error for missing successor")
	}
	if !errors.Is(err, ErrMissingSuccessor) {
		t.Fatalf("errors.Is missing successor failed: %v", err)
	}

	var wfErr *WorkflowError
	if !errors.As(err, &wfErr) {
		t.Fatalf("error %T should be WorkflowError", err)
	}
	if wfErr.Code != ErrCodeRoutingFailed {
		t.Fatalf("code = %s, want %s", wfErr.Code, ErrCodeRoutingFailed)
	}
}

func TestBatchNodeErrorEdges(t *testing.T) {
	prepErr := errors.New("prep failed")
	prepNode := NewBatchNode(NodeMeta{ID: "prep-fail"}).
		SetPrep(func(ctx *RunContext) ([]any, error) {
			return nil, prepErr
		})
	_, err := prepNode.Run(NewRunContext(context.Background(), nil, nil))
	if !errors.Is(err, prepErr) {
		t.Fatalf("prep error = %v, want %v", err, prepErr)
	}

	postErr := errors.New("post failed")
	postNode := NewBatchNode(NodeMeta{ID: "post-fail"}).
		SetPrep(func(ctx *RunContext) ([]any, error) {
			return []any{1}, nil
		}).
		SetPost(func(ctx *RunContext, items []any, results []any) (string, error) {
			return "", postErr
		})
	_, err = postNode.Run(NewRunContext(context.Background(), nil, nil))
	if !errors.Is(err, postErr) {
		t.Fatalf("post error = %v, want %v", err, postErr)
	}

	fallbackErr := errors.New("fallback failed")
	fallbackNode := NewBatchNode(NodeMeta{ID: "fallback-fail"}).
		SetPrep(func(ctx *RunContext) ([]any, error) {
			return []any{1}, nil
		}).
		SetExecItem(func(ctx *RunContext, item any, index int) (any, error) {
			return nil, errors.New("exec failed")
		}).
		SetFallbackItem(func(ctx *RunContext, item any, index int, lastErr error) (any, error) {
			return nil, fallbackErr
		})
	_, err = fallbackNode.Run(NewRunContext(context.Background(), nil, nil))
	if !errors.Is(err, fallbackErr) {
		t.Fatalf("fallback error = %v, want %v", err, fallbackErr)
	}
}

func TestParallelBatchNodePostError(t *testing.T) {
	postErr := errors.New("parallel post failed")
	node := NewParallelBatchNode(NodeMeta{ID: "parallel-post-fail"}, 2)
	node.SetPrep(func(ctx *RunContext) ([]any, error) {
		return []any{1, 2}, nil
	})
	node.SetPost(func(ctx *RunContext, items []any, results []any) (string, error) {
		return "", postErr
	})

	_, err := node.Run(NewRunContext(context.Background(), nil, nil))
	if !errors.Is(err, postErr) {
		t.Fatalf("post error = %v, want %v", err, postErr)
	}
}

func TestWorkflowErrorFormattingAndWrapNil(t *testing.T) {
	if err := wrapErr(StageExec, "node", "ignored", nil); err != nil {
		t.Fatalf("wrapErr(nil) = %v, want nil", err)
	}

	err := (&WorkflowError{Code: ErrCodeExecFailed, Stage: StageExec, NodeID: "node", Msg: "message"}).Error()
	if !strings.Contains(err, "code=exec_failed") || !strings.Contains(err, "stage=exec") || strings.Contains(err, "cause=") {
		t.Fatalf("unexpected WorkflowError string: %s", err)
	}
}

func TestRetryPolicyDelayAndValidation(t *testing.T) {
	policy := RetryPolicy{
		MaxRetries: 4,
		Wait:       10 * time.Millisecond,
		MaxWait:    25 * time.Millisecond,
		Backoff:    BackoffExponential,
	}

	if got := policy.Delay(0); got != 10*time.Millisecond {
		t.Fatalf("Delay(0) = %s, want 10ms", got)
	}
	if got := policy.Delay(1); got != 20*time.Millisecond {
		t.Fatalf("Delay(1) = %s, want 20ms", got)
	}
	if got := policy.Delay(2); got != 25*time.Millisecond {
		t.Fatalf("Delay(2) = %s, want capped 25ms", got)
	}

	node := NewFuncNode(NodeMeta{ID: "retry-policy"})
	node.Core().SetRetryPolicy(policy)
	if got := node.Core().Retry().Backoff; got != BackoffExponential {
		t.Fatalf("Backoff = %s, want %s", got, BackoffExponential)
	}

	jitterPolicy := RetryPolicy{
		MaxRetries: 2,
		Wait:       10 * time.Millisecond,
		Jitter:     time.Nanosecond,
	}
	if got := jitterPolicy.Delay(0); got < 10*time.Millisecond || got > 10*time.Millisecond+time.Nanosecond {
		t.Fatalf("jitter delay = %s, want [10ms, 10ms+1ns]", got)
	}
}

func TestCoreAndFlowOptionPanicsAndDefaults(t *testing.T) {
	mustPanic(t, func() {
		NewFlow("", nil)
	})
	mustPanic(t, func() {
		NewCoreNode(NodeMeta{})
	})
	mustPanic(t, func() {
		NewFuncNode(NodeMeta{ID: "retry"}).Core().SetRetry(0, 0)
	})
	mustPanic(t, func() {
		NewFuncNode(NodeMeta{ID: "retry"}).Core().SetRetry(1, -time.Nanosecond)
	})
	mustPanic(t, func() {
		NewFuncNode(NodeMeta{ID: "retry"}).Core().SetRetryPolicy(RetryPolicy{MaxRetries: 1, Backoff: "bad"})
	})
	mustPanic(t, func() {
		NewFuncNode(NodeMeta{ID: "timeout"}).Core().SetTimeout(-time.Nanosecond)
	})
	mustPanic(t, func() {
		NewFlow("timeout", NewFuncNode(NodeMeta{ID: "start"})).SetTimeout(-time.Nanosecond)
	})
	mustPanic(t, func() {
		NewFuncNode(NodeMeta{ID: "next"}).Core().NextAction("x", nil)
	})

	flow := NewFlow("timeout", NewFuncNode(NodeMeta{ID: "start"})).SetTimeout(time.Second)
	if got := flow.Timeout(); got != time.Second {
		t.Fatalf("Flow.Timeout() = %s, want 1s", got)
	}

	parallelNode := NewParallelBatchNode(NodeMeta{ID: "default-parallel"}, 0)
	if parallelNode.MaxConcurrency != 8 {
		t.Fatalf("default MaxConcurrency = %d, want 8", parallelNode.MaxConcurrency)
	}

	parallelFlow := NewParallelBatchFlow("default-parallel-flow", NewFuncNode(NodeMeta{ID: "start"}), 0)
	if parallelFlow.MaxConcurrency != 8 {
		t.Fatalf("default flow MaxConcurrency = %d, want 8", parallelFlow.MaxConcurrency)
	}
}

func TestErrorReturningConstructors(t *testing.T) {
	if _, err := NewFlowE("", nil); err == nil {
		t.Fatal("NewFlowE expected error")
	}
	if _, err := NewCoreNodeE(NodeMeta{}); err == nil {
		t.Fatal("NewCoreNodeE expected error")
	}
	if _, err := NewFuncNodeE(NodeMeta{}); err == nil {
		t.Fatal("NewFuncNodeE expected error")
	}
	if _, err := NewBatchNodeE(NodeMeta{}); err == nil {
		t.Fatal("NewBatchNodeE expected error")
	}
	if _, err := NewParallelBatchNodeE(NodeMeta{}, 1); err == nil {
		t.Fatal("NewParallelBatchNodeE expected error")
	}
	if _, err := NewBatchFlowE("", nil); err == nil {
		t.Fatal("NewBatchFlowE expected error")
	}
	if _, err := NewParallelBatchFlowE("", nil, 1); err == nil {
		t.Fatal("NewParallelBatchFlowE expected error")
	}

	if _, err := NewFlowE("ok", nil); err != nil {
		t.Fatalf("NewFlowE returned error: %v", err)
	}
	if _, err := NewFuncNodeE(NodeMeta{ID: "ok"}); err != nil {
		t.Fatalf("NewFuncNodeE returned error: %v", err)
	}
	if _, err := NewBatchNodeE(NodeMeta{ID: "ok"}); err != nil {
		t.Fatalf("NewBatchNodeE returned error: %v", err)
	}
	if _, err := NewParallelBatchNodeE(NodeMeta{ID: "ok"}, 1); err != nil {
		t.Fatalf("NewParallelBatchNodeE returned error: %v", err)
	}
}

func TestDefaultBatchFlows(t *testing.T) {
	start := NewFuncNode(NodeMeta{ID: "start"})

	action, err := NewBatchFlow("default-batch", start).RunWithContext(NewRunContext(context.Background(), nil, nil))
	if err != nil {
		t.Fatalf("BatchFlow returned error: %v", err)
	}
	if action != DefaultAction {
		t.Fatalf("BatchFlow action = %q, want %q", action, DefaultAction)
	}

	action, err = NewParallelBatchFlow("default-parallel-batch", start, 0).RunWithContext(NewRunContext(context.Background(), nil, nil))
	if err != nil {
		t.Fatalf("ParallelBatchFlow returned error: %v", err)
	}
	if action != DefaultAction {
		t.Fatalf("ParallelBatchFlow action = %q, want %q", action, DefaultAction)
	}
}

func TestParallelRuntimeNormalizesInvalidMaxConcurrency(t *testing.T) {
	node := NewParallelBatchNode(NodeMeta{ID: "runtime-parallel-node"}, 2)
	node.MaxConcurrency = 0
	node.SetPrep(func(ctx *RunContext) ([]any, error) {
		return []any{1, 2, 3}, nil
	})
	node.SetExecItem(func(ctx *RunContext, item any, index int) (any, error) {
		return item, nil
	})
	node.SetPost(func(ctx *RunContext, items []any, results []any) (string, error) {
		if !reflect.DeepEqual(results, []any{1, 2, 3}) {
			t.Fatalf("results = %#v, want [1 2 3]", results)
		}
		return "done", nil
	})

	action, err := node.Run(NewRunContext(context.Background(), nil, nil))
	if err != nil {
		t.Fatalf("ParallelBatchNode returned error: %v", err)
	}
	if action != "done" {
		t.Fatalf("action = %q, want done", action)
	}

	start := NewFuncNode(NodeMeta{ID: "runtime-parallel-flow-start"}).
		SetExec(func(ctx *RunContext, prepResult any) (any, error) {
			return nil, nil
		})
	flow := NewParallelBatchFlow("runtime-parallel-flow", start, 2)
	flow.MaxConcurrency = -1
	flow.SetPrepBatch(func(ctx *RunContext) ([]Params, error) {
		return []Params{{"id": 1}, {"id": 2}}, nil
	})
	flow.SetPostBatch(func(ctx *RunContext, batchParams []Params) (string, error) {
		return "flow_done", nil
	})

	action, err = flow.RunWithContext(NewRunContext(context.Background(), nil, nil))
	if err != nil {
		t.Fatalf("ParallelBatchFlow returned error: %v", err)
	}
	if action != "flow_done" {
		t.Fatalf("action = %q, want flow_done", action)
	}
}

func TestValidationErrorEmptyFormatting(t *testing.T) {
	err := (*ValidationError)(nil).Error()
	if err != "workflow validation failed" {
		t.Fatalf("nil ValidationError string = %q", err)
	}
}

func TestParallelChainMethodsReturnConcreteTypes(t *testing.T) {
	parallelNode := NewParallelBatchNode(NodeMeta{ID: "chain-node"}, 2).
		SetPrep(func(ctx *RunContext) ([]any, error) { return []any{1}, nil }).
		SetExecItem(func(ctx *RunContext, item any, index int) (any, error) { return item, nil }).
		SetFallbackItem(func(ctx *RunContext, item any, index int, lastErr error) (any, error) { return item, nil }).
		SetPost(func(ctx *RunContext, items []any, results []any) (string, error) { return DefaultAction, nil })

	if _, ok := any(parallelNode).(*ParallelBatchNode); !ok {
		t.Fatalf("chain result type = %T, want *ParallelBatchNode", parallelNode)
	}

	start := NewFuncNode(NodeMeta{ID: "chain-flow-start"})
	parallelFlow := NewParallelBatchFlow("chain-flow", start, 2).
		SetPrepBatch(func(ctx *RunContext) ([]Params, error) { return []Params{{}}, nil }).
		SetPostBatch(func(ctx *RunContext, batchParams []Params) (string, error) { return DefaultAction, nil })

	if _, ok := any(parallelFlow).(*ParallelBatchFlow); !ok {
		t.Fatalf("chain result type = %T, want *ParallelBatchFlow", parallelFlow)
	}
}

type nilCoreNode struct{}

func (nilCoreNode) Core() *CoreNode {
	return nil
}

func (nilCoreNode) Run(ctx *RunContext) (string, error) {
	return "", nil
}

func mustPanic(t *testing.T, f func()) {
	t.Helper()

	defer func() {
		if recover() == nil {
			t.Fatal("expected panic")
		}
	}()

	f()
}

func receiveEventType(t *testing.T, events <-chan Event) EventType {
	t.Helper()

	select {
	case event := <-events:
		return event.Type
	case <-time.After(time.Second):
		t.Fatal("timed out waiting for event")
		return ""
	}
}
