package workflow

import (
	"bytes"
	"context"
	"errors"
	"log"
	"strings"
	"testing"
	"time"
)

func TestNewRunContextGeneratesRunID(t *testing.T) {
	rc := NewRunContext(nil, nil, nil)
	if rc.RunID == "" {
		t.Fatal("RunID should be generated by default")
	}
	if rc.Context == nil {
		t.Fatal("Context should default to context.Background")
	}
	if rc.Shared == nil {
		t.Fatal("Shared should default to a non-nil store")
	}
}

func TestEventSinkPanicIsRecovered(t *testing.T) {
	var logs bytes.Buffer
	rc := NewRunContext(context.Background(), nil, nil)
	rc.Logger = log.New(&logs, "", 0)
	rc.Events = EventSinkFunc(func(event Event) {
		panic("sink failed")
	})

	rc.Emit(Event{Type: EventFlowStarted})

	if !strings.Contains(logs.String(), "workflow event sink panic") {
		t.Fatalf("expected event sink panic log, got %q", logs.String())
	}
}

func TestFlowValidate(t *testing.T) {
	t.Run("valid graph", func(t *testing.T) {
		start := NewFuncNode(NodeMeta{ID: "start"})
		end := NewFuncNode(NodeMeta{ID: "end"})
		start.Core().Next(end)

		if err := NewFlow("valid", start).Validate(); err != nil {
			t.Fatalf("Validate returned error: %v", err)
		}
	})

	t.Run("nil start", func(t *testing.T) {
		err := NewFlow("invalid", nil).Validate()
		if err == nil {
			t.Fatal("Validate expected error, got nil")
		}
		var validationErr *ValidationError
		if !errors.As(err, &validationErr) {
			t.Fatalf("error %T should be ValidationError", err)
		}
	})

	t.Run("duplicate node id", func(t *testing.T) {
		start := NewFuncNode(NodeMeta{ID: "start"})
		left := NewFuncNode(NodeMeta{ID: "dup"})
		right := NewFuncNode(NodeMeta{ID: "dup"})
		start.Core().NextAction("left", left)
		start.Core().NextAction("right", right)

		err := NewFlow("duplicate", start).Validate()
		if err == nil || !strings.Contains(err.Error(), "duplicate node id") {
			t.Fatalf("Validate error = %v, want duplicate node id", err)
		}
	})

	t.Run("cycle", func(t *testing.T) {
		a := NewFuncNode(NodeMeta{ID: "a"})
		b := NewFuncNode(NodeMeta{ID: "b"})
		a.Core().Next(b)
		b.Core().Next(a)

		err := NewFlow("cycle", a).Validate()
		if err == nil || !strings.Contains(err.Error(), "cycle") {
			t.Fatalf("Validate error = %v, want cycle", err)
		}
	})

	t.Run("nil successor", func(t *testing.T) {
		start := NewFuncNode(NodeMeta{ID: "start"})
		start.Core().mu.Lock()
		start.Core().successors["nil"] = nil
		start.Core().mu.Unlock()

		err := NewFlow("nil-successor", start).Validate()
		if err == nil || !strings.Contains(err.Error(), "successor node is nil") {
			t.Fatalf("Validate error = %v, want nil successor", err)
		}
	})

	t.Run("nil flow and nil core", func(t *testing.T) {
		var flow *Flow
		if err := flow.Validate(); err == nil {
			t.Fatal("nil flow Validate expected error, got nil")
		}

		err := NewFlow("nil-core", nilCoreNode{}).Validate()
		if err == nil || !strings.Contains(err.Error(), "node core is nil") {
			t.Fatalf("Validate error = %v, want nil core", err)
		}
	})
}

func TestFuncNodePanicIsWorkflowError(t *testing.T) {
	var events []Event
	node := NewFuncNode(NodeMeta{ID: "panic-node"}).
		SetExec(func(ctx *RunContext, prepResult any) (any, error) {
			panic("exec exploded")
		})

	rc := NewRunContext(context.Background(), nil, nil)
	rc.Events = EventSinkFunc(func(event Event) {
		events = append(events, event)
	})

	_, err := node.Run(rc)
	if err == nil {
		t.Fatal("Run expected error, got nil")
	}

	var wfErr *WorkflowError
	if !errors.As(err, &wfErr) {
		t.Fatalf("error %T should be WorkflowError", err)
	}
	if wfErr.Stage != StagePanic || wfErr.NodeID != "panic-node" {
		t.Fatalf("WorkflowError = stage:%s node:%s, want panic/panic-node", wfErr.Stage, wfErr.NodeID)
	}
	if wfErr.Stack == "" {
		t.Fatal("panic WorkflowError should include stack")
	}
	if len(events) != 2 || events[1].Type != EventNodeFailed {
		t.Fatalf("events = %#v, want node started then failed", events)
	}
}

func TestBatchFlowPanicIsWorkflowError(t *testing.T) {
	start := NewFuncNode(NodeMeta{ID: "start"})
	flow := NewBatchFlow("panic-batch-flow", start).
		SetPrepBatch(func(ctx *RunContext) ([]Params, error) {
			panic("prep batch exploded")
		})

	_, err := flow.RunWithContext(NewRunContext(context.Background(), nil, nil))
	if err == nil {
		t.Fatal("RunWithContext expected error, got nil")
	}

	var wfErr *WorkflowError
	if !errors.As(err, &wfErr) {
		t.Fatalf("error %T should be WorkflowError", err)
	}
	if wfErr.Stage != StagePanic {
		t.Fatalf("stage = %s, want panic", wfErr.Stage)
	}
}

func TestNodeTimeout(t *testing.T) {
	node := NewFuncNode(NodeMeta{ID: "timeout"}).
		SetExec(func(ctx *RunContext, prepResult any) (any, error) {
			<-ctx.Done()
			return nil, nil
		})
	node.Core().SetTimeout(10 * time.Millisecond)

	flow := NewFlow("timeout-flow", node)
	_, err := flow.RunWithContext(NewRunContext(context.Background(), nil, nil))
	if err == nil {
		t.Fatal("RunWithContext expected timeout error, got nil")
	}

	var wfErr *WorkflowError
	if !errors.As(err, &wfErr) {
		t.Fatalf("error %T should be WorkflowError", err)
	}
	if wfErr.Stage != StageFlow || wfErr.NodeID != "timeout" {
		t.Fatalf("WorkflowError = stage:%s node:%s, want flow/timeout", wfErr.Stage, wfErr.NodeID)
	}
}

func TestFlowAndNodeErrorEdges(t *testing.T) {
	if _, err := NewFlow("nil-start", nil).RunWithContext(nil); err == nil {
		t.Fatal("nil start flow should return error")
	}

	cancelled, cancel := context.WithCancel(context.Background())
	cancel()
	node := NewFuncNode(NodeMeta{ID: "cancelled"})
	_, err := NewFlow("cancelled-flow", node).RunWithContext(NewRunContext(cancelled, nil, nil))
	if err == nil {
		t.Fatal("cancelled context should return error")
	}

	var wfErr *WorkflowError
	if !errors.As(err, &wfErr) || wfErr.Stage != StageFlow {
		t.Fatalf("error = %v, want flow WorkflowError", err)
	}

	if err := sleepContext(cancelled, time.Second); err == nil {
		t.Fatal("sleepContext should return cancellation error")
	}
}

func TestBatchNodeErrorEdges(t *testing.T) {
	prepErr := errors.New("prep failed")
	prepNode := NewBatchNode(NodeMeta{ID: "prep-fail"}).
		SetPrep(func(ctx *RunContext) ([]any, error) {
			return nil, prepErr
		})
	_, err := prepNode.Run(NewRunContext(context.Background(), nil, nil))
	if !errors.Is(err, prepErr) {
		t.Fatalf("prep error = %v, want %v", err, prepErr)
	}

	postErr := errors.New("post failed")
	postNode := NewBatchNode(NodeMeta{ID: "post-fail"}).
		SetPrep(func(ctx *RunContext) ([]any, error) {
			return []any{1}, nil
		}).
		SetPost(func(ctx *RunContext, items []any, results []any) (string, error) {
			return "", postErr
		})
	_, err = postNode.Run(NewRunContext(context.Background(), nil, nil))
	if !errors.Is(err, postErr) {
		t.Fatalf("post error = %v, want %v", err, postErr)
	}

	fallbackErr := errors.New("fallback failed")
	fallbackNode := NewBatchNode(NodeMeta{ID: "fallback-fail"}).
		SetPrep(func(ctx *RunContext) ([]any, error) {
			return []any{1}, nil
		}).
		SetExecItem(func(ctx *RunContext, item any, index int) (any, error) {
			return nil, errors.New("exec failed")
		}).
		SetFallbackItem(func(ctx *RunContext, item any, index int, lastErr error) (any, error) {
			return nil, fallbackErr
		})
	_, err = fallbackNode.Run(NewRunContext(context.Background(), nil, nil))
	if !errors.Is(err, fallbackErr) {
		t.Fatalf("fallback error = %v, want %v", err, fallbackErr)
	}
}

func TestParallelBatchNodePostError(t *testing.T) {
	postErr := errors.New("parallel post failed")
	node := NewParallelBatchNode(NodeMeta{ID: "parallel-post-fail"}, 2)
	node.SetPrep(func(ctx *RunContext) ([]any, error) {
		return []any{1, 2}, nil
	})
	node.SetPost(func(ctx *RunContext, items []any, results []any) (string, error) {
		return "", postErr
	})

	_, err := node.Run(NewRunContext(context.Background(), nil, nil))
	if !errors.Is(err, postErr) {
		t.Fatalf("post error = %v, want %v", err, postErr)
	}
}

func TestWorkflowErrorFormattingAndWrapNil(t *testing.T) {
	if err := wrapErr(StageExec, "node", "ignored", nil); err != nil {
		t.Fatalf("wrapErr(nil) = %v, want nil", err)
	}

	err := (&WorkflowError{Stage: StageExec, NodeID: "node", Msg: "message"}).Error()
	if !strings.Contains(err, "stage=exec") || strings.Contains(err, "cause=") {
		t.Fatalf("unexpected WorkflowError string: %s", err)
	}
}

type nilCoreNode struct{}

func (nilCoreNode) Core() *CoreNode {
	return nil
}

func (nilCoreNode) Run(ctx *RunContext) (string, error) {
	return "", nil
}
